service: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    AWS_REGION_VAR: ${self:provider.region}
    MAIL_USERNAME: ${file(credentials/mail.txt)}
    MAIL_PASSWORD: ${file(credentials/password.txt)}
    OAUTH_CLIENTID: ${file(credentials/clientid.txt)}
    OAUTH_CLIENT_SECRET: ${file(credentials/clientsecret.txt)}
    OAUTH_REFRESH_TOKEN: ${file(credentials/refresh.txt)}
  memorySize: 256
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/MailQueueIAM.yml):MailQueueIAM}


resources:
  Resources:
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
